spring.application.name=legacyvault

spring.datasource.url=jdbc:postgresql://localhost:5432/legacyvault
spring.datasource.username=aaryanmiraje

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true